### ISSUE TITLE
Error if labels are not used is unclear

### ISSUE THREAD

**Issue by ccchwang** [Dan503/time-input-polyfill#2]
I'm trying to use this library in Safari and running into this error: `undefined is not an object (evaluating 'l(e).textContent')`. Points me to `index.js:29` which says:

![Screen Shot 2019-05-06 at 6 25 21 PM](https://user-images.githubusercontent.com/22921416/57259073-5812a680-702c-11e9-8d9b-5fb001f123c9.png)

Any thoughts? I've added the package through CDN and imported it into my JS. Would appreciate any help!

**Comment by Dan503** [comment]
Sorry to hear you are getting this error. ☹

I'm not going to be able to fix this myself because I don't have a Mac.

If you are able to figure out what is going wrong then I might be able to fix it.

**Comment by ccchwang** [comment]
I realize it's because my inputs didn't have an associated `<label>`, so `get_label($input).textContent` was returning an error. I know it makes sense to have this from an accessibility perspective, so maybe add to the docs that you need a label?

**Comment by Dan503** [comment]
Thanks for figuring out what the issue was. 

I think I might both update the docs and throw a clearer error message if there is no label attached to the input.

**Comment by Dan503** [comment]
Fixed in v1.0.5
